name: Deploy to Render

on:
  push:
    branches:
      - main  # or the branch you're working on

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        flask db migrate -m "Add uploaded_files to Report"
        flask db upgrade

    - name: Deploy to Render
      run: |
        curl -fsSL https://render.com/deploy/scripts/github-actions.sh | bash
      env:
        RENDER_TOKEN: ${{ secrets.RENDER_TOKEN }}
